from enum import Enum, unique


@unique
class Severity(str, Enum):
    DEBUG = "DEBUG"
    INFO = "INFO"
    WARNING = "WARNING"
    ERROR = "ERROR"
    CRITICAL = "CRITICAL"


@unique
class EventType(str, Enum):
    SYSTEM_START = "SYSTEM_START"
    SYSTEM_READY = "SYSTEM_READY"
    SYSTEM_STOP = "SYSTEM_STOP"
    SYSTEM_ERROR = "SYSTEM_ERROR"
    JARVIS_ENABLED = "JARVIS_ENABLED"
    JARVIS_DISABLED = "JARVIS_DISABLED"
    REQUEST_RECEIVED = "REQUEST_RECEIVED"
    REQUEST_COMPLETED = "REQUEST_COMPLETED"
    REQUEST_FAILED = "REQUEST_FAILED"
    MODEL_REQUEST = "MODEL_REQUEST"
    MODEL_RESPONSE = "MODEL_RESPONSE"
    AGENT_STARTED = "AGENT_STARTED"
    AGENT_COMPLETED = "AGENT_COMPLETED"
    POLICY_EVALUATION = "POLICY_EVALUATION"
    POLICY_DENIED = "POLICY_DENIED"
    POLICY_ALLOWED = "POLICY_ALLOWED"
    CONFIRMATION_REQUIRED = "CONFIRMATION_REQUIRED"
    LEASE_ACQUIRED = "LEASE_ACQUIRED"
    LEASE_RELEASED = "LEASE_RELEASED"
    TOOL_INVOCATION = "TOOL_INVOCATION"
    TOOL_COMPLETED = "TOOL_COMPLETED"
    TOOL_FAILED = "TOOL_FAILED"
    RESOURCE_ADMISSION = "RESOURCE_ADMISSION"
    RESOURCE_OBSERVATION = "RESOURCE_OBSERVATION"
    RETRY_STARTED = "RETRY_STARTED"
    AUDIT_WRITE = "AUDIT_WRITE"
    OBSERVABILITY_FAILURE = "OBSERVABILITY_FAILURE"
    MEMORY = "MEMORY"
